### ISSUE TITLE
[coc.nvim] Error on active extension coc-ember: Error: process.chdir() is not allowed in extension sandbox

### ISSUE THREAD

**Issue by ezpuzz** [NullVoxPopuli/coc-ember#2]
`[coc.nvim] Error on active extension coc-ember: Error: process.chdir() is not allowed in extension sandbox`

on Windows 10

I get this when opening a handlebars template.

**Comment by ezpuzz** [comment]
I think this is related: https://github.com/sindresorhus/execa/issues/357

**Comment by ezpuzz** [comment]
workaround is to go in to coc-ember folder manually and run `yarn` then go in to `node_modules\@emberwatch\ember-language-server` and run `yarn` followed by `yarn compile`

there are errors because of windows compat (`rm`  does not exist for ember-language-server`

**Comment by ezpuzz** [comment]
the `doesFileExist` call is failing because execa can't run `test` on windows

**Comment by ezpuzz** [comment]
confirmed that when I delete the call and ensure things are installed correctly I get some completion from the ember-language-server

I had to use the vim-plug method of installation and run both yarn commands manually.

**Comment by ezpuzz** [comment]
@NullVoxPopuli yes, windows is not supported using `CocInstall` and when installed using other methods requires running yarn commands manually to get working.

**Comment by NullVoxPopuli** [comment]
I wonder if vim-plug line with a `do` would work?
or is it just coc-ember that isn't supported on windows? do other coc-things work?

**Comment by ezpuzz** [comment]
@NullVoxPopuli https://github.com/NullVoxPopuli/coc-ember/blob/master/src/index.ts#L141  this line is the problem, `test` executable doesn't exist on windows.

**Comment by NullVoxPopuli** [comment]
Ah! That makes sense. @ezpuzz, do you want to do a PR with a Windows version of that?

**Comment by ezpuzz** [comment]
@NullVoxPopuli  see #3

**Comment by NullVoxPopuli** [comment]
I think this is resolved?
