### ISSUE TITLE
Disabling Typed Templates

### ISSUE THREAD

**Issue by alexlafroscia** [NullVoxPopuli/coc-ember#35]
I suddenly started getting a LOT of errors from `typed-templates`. How can we disable that part of this plugin?

**Comment by NullVoxPopuli** [comment]
what sort of errors? what do they look like?
:-\
it's not meant to error at all 🤔

**Comment by alexlafroscia** [comment]
I guess I'd like to turn the whole thing off... we're not doing any kind of template typing and now my editor looks like this

<img width="1226" alt="Screen Shot 2020-05-22 at 2 53 02 PM" src="https://user-images.githubusercontent.com/1645881/82700312-f673a900-9c3b-11ea-98df-613cd37f16b0.png">

It's quite distracting!

**Comment by NullVoxPopuli** [comment]
oof. @lifeart, what could cause this?

**Comment by NullVoxPopuli** [comment]
@alexlafroscia in the meantime, you can disable it by cd'ing to your extensions directory/node_modules/coc-ember/lib/addons and rm'ing the typed templates addon

**Comment by lifeart** [comment]
@NullVoxPopuli, ya it's typed-templates, can't resolve global scoped `formId`.

**Comment by alexlafroscia** [comment]
I get that the issue, specifically, is that it can't source this variable. The problem isn't that -- it's that I don't want to run these checks at all on my codebase, because basically every file is going to have a ton of violations ☹️

**Comment by lifeart** [comment]
@alexlafroscia sort term fix is - add `{{!-- @ts-nocheck --}}` to files with issues.

**Comment by alexlafroscia** [comment]
That's.... 524 files that I'll need to add that to.

It would really just be great to be able to turn this feature of `coc-ember` off

**Comment by lifeart** [comment]
agree, sorry for such regression, I think @NullVoxPopuli will figure out way to configure addons selection.

**Comment by alexlafroscia** [comment]
No worries -- it's a great feature and I can't wait to use it! Unfortunately, it just doesn't play nicely for codebases that are still catching up to best-practices, like ours.

**Comment by NullVoxPopuli** [comment]
I think I'm gonna remove the addon for now

**Comment by NullVoxPopuli** [comment]
removed here: https://github.com/NullVoxPopuli/coc-ember/commit/bac594134d61463045b5c6713ce184daa0d5095f
